classes/urls.py
# it's advisable give your apps a default path too
# there can only be one default path per project and also per app


from django.urls import path

from . import views

app_name = "classes"
urlpatterns = [

    path('', views.Home, name="home"),
    path('about/', views.about, name="about"),
    path('contact/', views.contact, name="contact"),
    path('add', views.add, name="add"),
    path('viewdata', views.viewdata, name="viewdata"),
    path('delete/<id>', views.delete, name="delete"),
    path('insertdata', views.insertdata, name="insertdata"),
    path('edit/<id>', views.edit, name="edit"),
    path('details/<id>', views.details, name="details")
]

school/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
                  path('ezra/', admin.site.urls),
                  path('', include("classes.urls")),
                  path('students/', include("students.urls"))

              ]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

students/urls.py
from django.urls import path
from . import views


app_name = "students"
urlpatterns = [

    path('',views.Home, name= "Home")

]

classes/models.py
from django.db import models


# anytime you modify the models file, you must make and run migrations

class Student(models.Model):
    name = models.CharField(max_length=100, blank=False)
    email = models.EmailField()
    age = models.IntegerField()
    image = models.ImageField(upload_to='images', default='profile.png')


    def __str__(self):
        return self.name


class Teachers(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(default="description")

    def __str__(self):
        return self.name

students/models.py
from django.db import models

# Create your models here.

classes/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect

from .models import Student

import os


# Create your views here.

# here is where all functions are created


def Home(request):
    return render(request, 'home.html', {'navbar': 'home'})


def about(request):
    return render(request, 'about.html', {'navbar': 'about'})


def contact(request):
    return render(request, 'pages/contact.html', {'navbar': 'contact'})


def add(request):
    return render(request, 'add.html', {'navbar': 'add'})


def viewdata(request):
    students = Student.objects.all()
    return render(request, 'viewdata.html', {'navbar': 'viewdata', 'data': students})


def delete(request, id):
    student = Student.objects.get(id=id)
    student.delete()
    return redirect("/viewdata")


def insertdata(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        email = request.POST.get('email')
        age = request.POST.get('age')
        image = request.FILES['image']

        room = Student(name=name, email=email, age=age, image=image)
        room.save()
        return redirect("/viewdata")

    return redirect("/viewdata")


def edit(request, id):
    if request.method == 'POST':
        name = request.POST.get('name')
        email = request.POST.get('email')
        age = request.POST['age']
        image = request.FILES['image']

        student = Student.objects.get(id=id)

        student.name = name
        student.email = email
        student.age = age
        student.image = image

        if len(request.FILES) != 0:
            if len(student.image) > 0:
                student.image = request.FILES['image']

        student.save()
        return redirect("/viewdata")

    student = Student.objects.get(id=id)
    return render(request, 'edit.html', {'student':student})


def details(request, id):
    student = Student.objects.get(id=id)
    return render(request, 'details.html', {'student':student})

students/views.py
from django.shortcuts import render


# Create your views here.


def Home(request):
    return render(request, 'students.html', {'navbar':'students'})

classes/templates/about.html
{% extends 'layout.html' %}

{% load static %}

{% block body %}

    <p>about page</p>

     <img src="{% static 'images/logo.png' %}" alt="all">

{% endblock %}

classes/templates/add.html
{% extends 'layout.html' %}

{% block body %}


    <div class="container">

    <h2 class="mt-5">Add student</h2>

        <form action="/insertdata" method="post" class="mt-2" enctype="multipart/form-data">

            {% csrf_token %}

            <div class="mb-3">
                <label  class="form-label">Name</label>
                <input type="text" class="form-control"  placeholder="Name" name="name" required>
            </div>

            <div class="mb-3">
                <label  class="form-label">Email</label>
                <input type="email" class="form-control"  placeholder="Email" name="email" required>
            </div>

            <div class="mb-3">
                <label  class="form-label">Age</label>
                <input type="number" class="form-control"  placeholder="Age" name="age" required>
            </div>

            <div class="mb-3">
                <label  class="form-label">Image</label>
                <input type="file" class="form-control" name="image" required>

            </div>

            <div class="mb-3">
                <input type="submit" class="form-control btn btn-success" value="Submit">
            </div>

        </form>

    </div>


{% endblock %}

classes/templates/details.html
{% extends 'layout.html' %}

{% block body %}

    <p>{{ student.name }}</p>
    <p>{{ student.age }}</p>
    <p>{{ student.email }}</p>
    <img src="/media/{{ student.image }}" alt="">

{% endblock %}

classes/templates/edit.html
{% extends 'layout.html' %}

{% block body %}


    <div class="container">

    <h2 class="mt-5">Edit student</h2>

        <form action="" method="POST" class="mt-2" enctype="multipart/form-data">

            {% csrf_token %}

            <div class="mb-3">
                <label  class="form-label">Name</label>
                <input type="text" class="form-control"  placeholder="Name" name="name" value="{{ student.name }}" required>
            </div>

            <div class="mb-3">
                <label  class="form-label">Email</label>
                <input type="email" class="form-control"  placeholder="Email" name="email" value="{{ student.email }}" required>
            </div>

            <div class="mb-3">
                <label  class="form-label">Age</label>
                <input type="number" class="form-control"  placeholder="Age" name="age" value="{{ student.age }}" required>
            </div>

            <div class="mb-3">
                <label  class="form-label">Image</label>
                <img src="/media/{{ student.image }}" alt="">
                <input type="file" class="form-control" name="image" required>

            </div>

            <div class="mb-3">
                <input type="submit" class="form-control btn btn-success" value="Submit">
            </div>

        </form>

    </div>


{% endblock %}

classes/templates/home.html
{% extends 'layout.html' %} {% load static %} {% block body %}

<div>
  {% for data in data %}

  <p>{{ data.name}}</p>

  {% endfor %}
  <br /><br /><br /><br />
  <p>
    Lorem ipsum dolor sit amet, consectetur adipisicing elit. A commodi
    consequuntur cum dolore error est ex, explicabo fuga fugit minima
    necessitatibus nemo neque nobis non quo repellat suscipit tempora, totam.
  </p>
</div>

<h3 class="one">Disclaimer!</h3>
<p>You are not other developer. You're a Django developer</p>

<img src="{% static 'images/logo.png' %}" alt="all" />

<button class="btn btn-success">Button</button>

<input type="text" class="form-control" />

{% endblock %}

classes/templates/layout.html
{% load static %}

<!doctype html>
<html lang="en">
<head>

    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <style>
        .ones{
            height: 300px;
            width: 300px;
            background-image: url("{% static 'images/logo.png' %}");
            background-repeat: no-repeat;
        }
        .two{
    color: red;
    background: yellow;
    border-radius: 5px;
}

    </style>

    <link rel="stylesheet" href="{% static 'css/styles.css' %}">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>



</head>
<body>

{#static files:#}

{#this is the django recommended way of routing#}

<a class="{% if navbar == 'home' %} two {% endif %}" href="{% url 'classes:home' %}">Home</a>
<a class="{% if navbar == 'about' %} two {% endif %}" href="{% url 'classes:about' %}">About</a>
<a class="{% if navbar == 'contact' %} two {% endif %}" href="{% url 'classes:contact' %}">Contact</a>
<a class="{% if navbar == 'students' %} two {% endif %}" href="{% url 'students:Home' %}">Students</a>
<a  class="{% if navbar == 'add' %} two {% endif %}" href="{% url 'classes:add' %}">Add Data</a>
<a  class="{% if navbar == 'viewdata' %} two {% endif %}" href="{% url 'classes:viewdata' %}">View Data</a>





{% block body %}


{% endblock %}


</body>
</html>

classes/templates/modal.html
<button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
  Delete
</button>

<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">

    <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="staticBackdropLabel">{{ dd.name }}</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Are you sure you to delete {{ dd.name }}?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
       <a class="btn btn-danger" href="/delete/{{ dd.id }}">Delete</a>
      </div>
    </div>
  </div>

</div>

classes/templates/pages/contact.html
{% extends 'layout.html' %}

{% block body %}

    <p>contact page</p>


{% endblock %}

classes/templates/viewdata.html
{% extends 'layout.html' %}

{% block body %}


    <div class="container">

    <h2 class="mt-5">Students - Tabular</h2>

        <table class="table mt-2">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Email</th>
      <th scope="col">Age</th>
        <th scope="col">Image</th>
        <th scope="col">Edit</th>
        <th scope="col">Delete</th>
    </tr>
  </thead>
  <tbody>

  {% for dd in data %}

                  {% csrf_token %}
      <tr>
         <th scope="row">{{ dd.id }}</th>
         <td>{{ dd.name }}</td>
         <td>{{ dd.email }}</td>
         <td>{{ dd.age }}</td>
         <td>
             <img src="http://127.0.0.1:8000/media/{{ dd.image }}" alt="{{ dd.name }}" width="70">
         </td>
          <td>
              <a class="btn btn-warning" href="edit/{{ dd.id }}">Edit</a>
          </td>
          <td>
              <a class="btn btn-danger" href="/delete/{{ dd.id }}">Delete</a>

          </td>



      </tr>

  {% endfor %}

  </tbody>

</table>

    <h2 class="mt-5">Students - Grids</h2>

    <div class="row">

        {% for dd in data %}

        <div class="col-md-3">
            <div class="card mb-3">
             <img src="http://127.0.0.1:8000/media/{{ dd.image }}" class="card-img-top" alt="{{ dd.name }}">
                <div class="card-body">
                <p class="card-text">{{ dd.name }}</p>
                    <p class="card-text">{{ dd.email }}</p>
                    <p class="card-text">{{ dd.age }}</p>
                </div>
            </div>
        </div>

        {% endfor %}
    <p class="card-text">{{ dd.name }}</p>
    </div>





    </div>

<br><br><br><br><br><br><br>
{% endblock %}

students/templates/students.html
{% extends 'layout.html' %}



{% block body %}

<p>Students app</p>

{% endblock %}